options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _MLOPS_BUILD_IMAGE: 'europe-west1-docker.pkg.dev/mlops-241257/mlops-build/mlops-build:1.1.0'
  _STREAMLIT_IMAGE: 'europe-west1-docker.pkg.dev/mlops-241257/mlops-images/mlops-streamlit'
  _DOCKER_IMAGE: 'gcr.io/cloud-builders/docker'

steps:
  # 1. Compile pipeline
  - name: '${_MLOPS_BUILD_IMAGE}'
    id: Compile pipeline
    entrypoint: python
    args: ['kubeFlow/pipeline.py']

  # 2. Submit pipeline
  - name: '${_MLOPS_BUILD_IMAGE}'
    id: Submit pipeline
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        echo "Branch name: '${BRANCH_NAME}'"
        if [ "${BRANCH_NAME}" = "production" ]; then ENV="prod"; else ENV="dev"; fi
        echo "Environment: '$$ENV'"
        ENV="$$ENV" python kubeFlow/submit.py

  # 3. Run test cases
  - name: '${_MLOPS_BUILD_IMAGE}'
    id: Run unit tests
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        if [ "${BRANCH_NAME}" = "production" ]; then export ENV="prod"; else export ENV="dev"; fi
        pytest -q tests

  # 4. Build Streamlit image
  - name: '${_DOCKER_IMAGE}'
    id: Build image
    args: ['build', '-t', '${_STREAMLIT_IMAGE}:$BUILD_ID', '.']

  # 5. Push image
  - name: '${_DOCKER_IMAGE}'
    id: Push image
    args: ['push', '${_STREAMLIT_IMAGE}:$BUILD_ID']

  # 6. Deploy to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: Deploy to GKE
    entrypoint: bash
    args:
      - -c
      - |
        if [ "$BRANCH_NAME" = "production" ]; then
          gke-deploy run \
            --filename=k8s/ \
            --image="${_STREAMLIT_IMAGE}:$BUILD_ID" \
            --cluster=mlops-cluster \
            --location=europe-west1-b \
            --namespace=default
        else
          echo "INFO: Skipping deployment."
          echo "INFO: Expected branch='production' but got '${BRANCH_NAME}'."
        fi

  # # 6. Deploy to GKE
  # - name: 'gcr.io/cloud-builders/gke-deploy'
  #   id: Deploy to GKE
  #   entrypoint: bash
  #   args:
  #     - -c
  #     - |
  #       gke-deploy run \
  #         --filename=k8s/ \
  #         --image="${_STREAMLIT_IMAGE}:$BUILD_ID" \
  #         --cluster=mlops-cluster \
  #         --location=europe-west1-b \
  #         --namespace=default


images:
  - '${_STREAMLIT_IMAGE}:$BUILD_ID'