options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: mlops-pipeline-01
  _ARTIFACT_REPO: mlops-images
  _ARTIFACT_HOST: europe-west1-docker.pkg.dev

steps:
  # 1. Compile pipeline
  - name: '${_ARTIFACT_HOST}/${_PROJECT_ID}/mlops-build/mlops-build:1.0.0'
    id: Compile pipeline
    entrypoint: python
    args:
      - kubeFlow/compile_pipeline.py

  # 2. Submit pipeline
  - name: '${_ARTIFACT_HOST}/${_PROJECT_ID}/mlops-build/mlops-build:1.0.0'
    id: Submit pipeline
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        echo "Branch name: '${BRANCH_NAME}'"
        if [ "${BRANCH_NAME}" = "production" ]; then ENV="prod"; else ENV="dev"; fi
        echo "Environment: '$$ENV'"
        ENV="$$ENV" python kubeFlow/submit.py


  # 3. Build Streamlit image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build image
    args:
      - build
      - -t
      - ${_ARTIFACT_HOST}/${_PROJECT_ID}/${_ARTIFACT_REPO}/mlops-streamlit:$BUILD_ID
      - .

  # 4. Push image
  - name: 'gcr.io/cloud-builders/docker'
    id: Push image
    args:
      - push
      - ${_ARTIFACT_HOST}/${_PROJECT_ID}/${_ARTIFACT_REPO}/mlops-streamlit:$BUILD_ID

  # 5. Deploy to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: Deploy to GKE
    # Only deploy the image when branch name = production
    entrypoint: bash
    args:
      - -c
      - |
        if [ "$BRANCH_NAME" = "production" ]; then
          gke-deploy run \
            --filename=k8s/ \
            --image=${_ARTIFACT_HOST}/${_PROJECT_ID}/${_ARTIFACT_REPO}/mlops-streamlit:$BUILD_ID \
            --cluster=mlops-cluster \
            --location=europe-west1-b \
            --namespace=default
        else
          echo "Deployment skipped. Not running on production branch. Current branch: $BRANCH_NAME"
        fi


images:
  - ${_ARTIFACT_HOST}/${_PROJECT_ID}/${_ARTIFACT_REPO}/mlops-streamlit:$BUILD_ID
