substitutions:
  _MODEL_ARTIFACT_URI: ""
  _SERVING_IMAGE_URI: "europe-docker.pkg.dev/mlops-pipeline-01/ml-images/knn-serving"
  _ENDPOINT_NAME: "knn-endpoint"

steps:
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - ${_SERVING_IMAGE_URI}:${BUILD_ID}
    - serving

- name: gcr.io/cloud-builders/docker
  args:
    - push
    - ${_SERVING_IMAGE_URI}:${BUILD_ID}

- name: python:3.11-slim
  entrypoint: bash
  args:
    - -c
    - |
      pip install -r deploy/requirements.txt
      python deploy/deploy_model.py
  env:
    - PROJECT_ID=mlops-pipeline-01
    - REGION=europe-west1
    - MODEL_ARTIFACT_URI=${_MODEL_ARTIFACT_URI}
    - SERVING_IMAGE_URI=${_SERVING_IMAGE_URI}:${BUILD_ID}
    - ENDPOINT_NAME=${_ENDPOINT_NAME}

images:
- ${_SERVING_IMAGE_URI}:${BUILD_ID}
