apiVersion: apps/v1
kind: Deployment
metadata:
  name: knn-inference
spec:
  replicas: 2
  selector:
    matchLabels:
      app: knn-inference
  template:
    metadata:
      labels:
        app: knn-inference
    spec:
      serviceAccountName: knn-inference-sa
      containers:
      - name: knn-inference
        image: europe-west1-docker.pkg.dev/mlops-pipeline-01/ml-images/knn-inference:1.0
        ports:
        - containerPort: 8080
