apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-streamlit
  namespace: mlops-serving
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-streamlit
  template:
    metadata:
      labels:
        app: mlops-streamlit
    spec:
      serviceAccountName: mlops-serving-ksa
      containers:
        - name: streamlit
          image: europe-west3-docker.pkg.dev/mlops-pipeline-01/mlops-images/mlops-streamlit:v1
          ports:
            - containerPort: 8080
          env:
            - name: MODEL_BUCKET
              value: "mlops-pipeline-01"
            - name: MODEL_GCS_PATH
              value: "dev/model/model.joblib"
