apiVersion: v1
kind: Service
metadata:
  name: mlops-streamlit-svc
  namespace: mlops-serving
spec:
  type: LoadBalancer
  selector:
    app: mlops-streamlit
  ports:
    - port: 80
      targetPort: 8080

